app:
    resource: '@AppBundle/Controller/'
    type: annotation
logout:
    path: /logout
upload:
    pattern:  /app/
    defaults: { _controller: AppBundle:GestionController:CargaMasiva }
    options:
        expose: true
    